package com.allanwang.lottery.domain.support.ids.policy;

import com.allanwang.lottery.domain.support.ids.IIdGenerator;
import org.apache.commons.lang3.RandomStringUtils;
import org.springframework.stereotype.Component;

/**
 * @description: generated by util class
 * org.apache.commons.lang3.RandomStringUtils
 *
 */
@Component
public class RandomNumeric implements IIdGenerator {

    @Override
    public long nextId() {
        return Long.parseLong(RandomStringUtils.randomNumeric(11));
    }

}

